### ISSUE TITLE
Testing suite

### ISSUE THREAD

**Issue by paddatrapper** [mayuso/Datuk#5]
Create a testing suite of unit tests and integration tests to ensure continued functionality. JUnit works very well for this and ties nicely into the maven infrastructure.

**Comment by mayuso** [comment]
I´m have close to no experience with Testing and JUnit. Will try to learn about it and take this into account.

**Comment by paddatrapper** [comment]
If I've got some time in the next couple of weeks I'll try make a start on it. I can't promise anything at this point though as my schedule is a little all over the place.

**Comment by mayuso** [comment]
That would be nice. I could really use some help too :)

One of the secondary goals of this project is to help me learn about technology, and Testing is an important part I never thought about, so I might include Tests in my plans for the near future and add them before the next release.

**Comment by mayuso** [comment]
I have seen a few "How to"s and I gave it my first try. Not really useful tests yet, but will get better eventually with time (and hopefully some help from people that are interested xD) (f24dce9)

**Comment by paddatrapper** [comment]
Started to address this in PR #6
